name: Migrations db

on: push

jobs:
  migrations:
    name: Migrations
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - shell: bash
        run: |
          echo "$DATABASE_URL"

      - name: bun install
        run: bun install

      - name: Run migrate file
        run: bun migrate
